### ISSUE TITLE
Can't install from pip

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/mbed-ls#18]
I get this error when install on Windows and Ubuntu:

```
Collecting mbed-ls
  Downloading mbed-ls-0.1.18.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\bridan01\appdata\local\temp\pip-build-4idhct\mbed-ls\setup.py", line 38, in <module>
        long_description=read('README.md'),
      File "c:\users\bridan01\appdata\local\temp\pip-build-4idhct\mbed-ls\setup.py", line 33, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    IOError: [Errno 2] No such file or directory: 'c:\\users\\bridan01\\appdata\\local\\temp\\pip-build-4idhct\\mbed-ls\\README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\bridan01\appdata\local\temp\pip-build-4idhct\mbed-ls
```

**Comment by 0xc0170** [comment]
Thanks for reporting, I was able to reproduce the problem locally. I'll send PR shortly
