### ISSUE TITLE
1.3.2 throws at launch, when installed in ArchLinux

### ISSUE THREAD

**Issue by RomanSaveljev** [ARMmbed/mbed-ls#246]
```
[alarm@wandboard ~]$ sudo -H pip2 install mbed-ls
Collecting mbed-ls
  Downloading mbed-ls-1.3.2.tar.gz (60kB)
    100% |################################| 61kB 364kB/s 
Collecting PrettyTable>=0.7.2 (from mbed-ls)
  Downloading prettytable-0.7.2.zip
Collecting fasteners (from mbed-ls)
  Downloading fasteners-0.14.1-py2.py3-none-any.whl
Requirement already satisfied: appdirs>=1.4 in /usr/lib/python2.7/site-packages (from mbed-ls)
Collecting monotonic>=0.1 (from fasteners->mbed-ls)
  Downloading monotonic-1.3-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from fasteners->mbed-ls)
Installing collected packages: PrettyTable, monotonic, fasteners, mbed-ls
  Running setup.py install for PrettyTable ... done
  Running setup.py install for mbed-ls ... done
Successfully installed PrettyTable-0.7.2 fasteners-0.14.1 mbed-ls-1.3.2 monotonic-1.3
[alarm@wandboard ~]$ mbedls
Traceback (most recent call last):
  File "/usr/bin/mbedls", line 11, in <module>
    load_entry_point('mbed-ls==1.3.2', 'console_scripts', 'mbedls')()
  File "/usr/lib/python2.7/site-packages/mbed_lstools/main.py", line 236, in mbedls_main
    start_logging()
  File "/usr/lib/python2.7/site-packages/mbed_lstools/main.py", line 230, in start_logging
    logging.basicConfig()
NameError: global name 'logging' is not defined
```

Had to revert to `1.2.14`.

**Comment by theotherjimmy** [comment]
Resolved by #245
