### ISSUE TITLE
Unmounted NRF52_DK shows error when `-u` is passed

### ISSUE THREAD

**Issue by drahnr** [ARMmbed/mbed-ls#325]
Trying to list all devices yields.
```
mbedls --json                                                                    15:22:32   1 
WARNING:mbedls.lstools_base:MBED with target id '000682416648' is connected, but not mounted. Use the '-u' flag to include it in the list.
[]
```
Following the suggestion causes this error:
```
mbedls --json --list-unmounted                                                   15:22:20   0 
Traceback (most recent call last):
  File "/home/bernhard/.local/bin//mbedls", line 11, in <module>
    load_entry_point('mbed-ls==1.4.2', 'console_scripts', 'mbedls')()
  File "/home/bernhard/.local/lib/python3.6/site-packages/mbed_lstools/main.py", line 262, in mbedls_main
    ret_code = args.command(mbeds, args)
  File "/home/bernhard/.local/lib/python3.6/site-packages/mbed_lstools/main.py", line 138, in mbeds_as_json
    read_details_txt=True),
  File "/home/bernhard/.local/lib/python3.6/site-packages/mbed_lstools/lstools_base.py", line 150, in list_mbeds
    name = device['platform_name']
KeyError: 'platform_name'
```

**Comment by bridadan** [comment]
Hi @drahnr, thanks for raising the issue. Can you provide the following so we can debug it?

1. Host OS version
1. Firmware running on the NRF52_DK (JLink, DAPLink, etc)
1. The output of `mbedls --debug --list-unmounted`
