### ISSUE TITLE
mbedls 1.4.6 hangs on macOS 10.13.5 Python3.6

### ISSUE THREAD

**Issue by cederom** [ARMmbed/mbed-ls#359]
Hello world :-) I have noticed a problem with `mbedls` on macOS and Python 3.6.5 virtualenv, it hangs with no results.. this also affects other tools that depend on `mbed-ls` :-)

```
(venv36) mbedls --version
1.4.6

(venv36) mbedls -d
DEBUG:mbedls.main:mbed-ls ver. 1.4.6
DEBUG:mbedls.main:host: ('posix', 'Darwin', '17.6.0', 'Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64', 'darwin')

<<nothing shows here>>

(venv36) python --version
Python 3.6.5
```

Seems to work well in Python 2.7 virtualenv:
```
(venv27) $ mbedls --version
1.3.7
(venv27) $ mbedls
+---------------+----------------------+------------------+-----------------------+--------------------------------------------------+-----------------+
| platform_name | platform_name_unique | mount_point      | serial_port           | target_id                                        | daplink_version |
+---------------+----------------------+------------------+-----------------------+--------------------------------------------------+-----------------+
| unknown       | None[0]              | /Volumes/DAPLINK | /dev/tty.usbmodem1412 | 110100004420312033504139313031313233303097969903 | 0244            |
+---------------+----------------------+------------------+-----------------------+--------------------------------------------------+-----------------+

(venv27) $ python --version
Python 2.7.14
```

```
$ mbedls --version
WARNING:mbedls.platform_database:Error loading database /Users/cederom/Library/Application Support/mbedls/platforms.json: Platform Database is out of date; Recreating
1.4.6
(venv27) $ mbedls
+---------------+----------------------+------------------+-----------------------+--------------------------------------------------+-----------------+
| platform_name | platform_name_unique | mount_point      | serial_port           | target_id                                        | daplink_version |
+---------------+----------------------+------------------+-----------------------+--------------------------------------------------+-----------------+
| NRF52_DK      | NRF52_DK[0]          | /Volumes/DAPLINK | /dev/tty.usbmodem1412 | 110100004420312033504139313031313233303097969903 | 0244            |
+---------------+----------------------+------------------+-----------------------+--------------------------------------------------+-----------------+

$ python --version
Python 2.7.15
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-892

**Comment by bridadan** [comment]
Huh, weird! Thanks for raising the issue. @theotherjimmy you have a Mac to test on right?

**Comment by cederom** [comment]
Always welcome @bridadan let me know if you need some more testing :-) I just heard about Python3 support so I wanted to try that out.. while trying `mbed sterm` did not get anything so I thought that would depend on `mbed-ls` and got into this issue.. in the meantime I am using `minicom` for serial console and that works fine.. so maybe a detection phase issue..? :-)

**Comment by theotherjimmy** [comment]
Maybe. I'll take a look.

**Comment by theotherjimmy** [comment]
Confirmed. It's getting stuck in an iosomething.wait()

**Comment by jupe** [comment]
this happens also with latest release:
```
$ mbedls -d
DEBUG:mbedls.main:mbed-ls ver. 1.5.1
DEBUG:mbedls.main:host: ('posix', 'Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64', 'darwin')
^CTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/mbedls", line 11, in <module>
    load_entry_point('mbed-ls==1.5.1', 'console_scripts', 'mbedls')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mbed_lstools/main.py", line 262, in mbedls_main
    ret_code = args.command(mbeds, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mbed_lstools/main.py", line 111, in print_table
    return print_mbeds(mbeds, args, False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mbed_lstools/main.py", line 98, in print_mbeds
    devices = mbeds.list_mbeds(unique_names=True, read_details_txt=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mbed_lstools/lstools_base.py", line 136, in list_mbeds
    candidates = list(self.find_candidates())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mbed_lstools/darwin.py", line 106, in find_candidates
    volumes = self._volumes()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mbed_lstools/darwin.py", line 159, in _volumes
    ioreg_usb.wait()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1436, in wait
    (pid, sts) = self._try_wait(0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1383, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

Any chance to get fix for this ?

**Comment by theotherjimmy** [comment]
I think this ([from here](https://docs.python.org/3/library/subprocess.html?highlight=subprocess#subprocess.Popen.wait)) is related:

>Note
>
>This will deadlock when using stdout=PIPE or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use Popen.communicate() when using pipes to avoid that.
